### ISSUE TITLE
add linters rules to ak

### ISSUE THREAD

**Issue by hparfr** [akretion/ak#107]
- each directory entry should be ordered
- directory entry should be unique
- module values should be ordered
- module values should be unique

```yaml
sale-workflow:
  modules:
     - sale_exception
     - base_exception
   src: https://github.com/oca/sale-workflow 16.0

product-attribute:
  modules:
     - purchase_exception
     - base_exception
  src: https://github.com/oca/purchase-exception 16.0
```

should be: 

```yaml

product-attribute:
  modules:
     - purchase_exception
  src: https://github.com/oca/purchase-exception 16.0

sale-workflow:
  modules:
     - base_exception
     - sale_exception

   src: https://github.com/oca/sale-workflow 16.0


```
